---
- name: "Install apt packages"
  package:
    name:
      - jq
      - pipx
      - ntpdate
      - flameshot
      - exiftool
      - lightdm-remote-session-freerdp2
    state: latest
  become: true
  become_method: sudo
