---
- name: "Install apt packages"
  package:
    name:
      - jq
      - pipx
      - ntpdate
      - flameshot
      - exiftool
      - lightdm-remote-session-freerdp2
    state: latest
  become: true
  become_method: sudo

- name: Download the Obsidian .deb package
  get_url:
    url: https://github.com/obsidianmd/obsidian-releases/releases/download/v1.6.7/obsidian_1.6.7_amd64.deb
    dest: /tmp/obsidian_1.6.7_amd64.deb

- name: Install the Obsidian .deb package
  apt:
     deb: /tmp/obsidian_1.6.7_amd64.deb
  become: true
  become_method: sudo

- name: Clean up the downloaded .deb package
  ansible.builtin.file:
    path: /tmp/obsidian_1.6.7_amd64.deb
    state: absent