---
- name: "Install pipx stuff"
  community.general.pipx:
    name: "{{ item.name }}"
    source: "{{ item.url }}"
    state: latest
  loop:
    - { name: 'impacket', url: 'git+https://github.com/fortra/impacket.git' }
    - { name: 'netexec', url: 'git+https://github.com/Pennyw0rth/NetExec' }
    - { name: 'certipy-ad', url: 'git+https://github.com/ly4k/Certipy.git' }
    - { name: 'arsenal', url: 'git+https://github.com/Orange-Cyberdefense/arsenal.git' }
  ignore_errors: yes