---
- name: "Copy the new wallpaper to the system"
  copy:
    src: "{{ role_path }}/files/Wallpaper.jpg"
    dest: "{{ ansible_env.HOME }}/Pictures/Wallpaper.jpg"
- name: "Setting new wallpaper"
  ansible.builtin.shell: 
    xfconf-query -c xfce4-desktop -p $(xfconf-query -c xfce4-desktop -l | grep "workspace0/last-image") -s "{{ ansible_env.HOME }}/Pictures/Wallpaper.jpg"
    